title: Michael Gugliotti
logo: https://raw.githubusercontent.com/googs0/googs0.github.io/main/assets/Profile_Picture_Orioles.jpg
description: Programming Portfolio
show_downloads: true
theme: jekyll-theme-minimal
markdown: kramdown
include:
  - _includes
scss:
  - assets/main.scss
  - |
    body {
      background-color: #fff;
      padding: 50px;
      font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
      color: #595959;
      font-weight: 400;
    }
