title: Michael Gugliotti
logo: https://raw.githubusercontent.com/googs0/googs0.github.io/main/assets/MG_Cropped.jpg
description: Programming Portfolio
show_downloads: true
theme: jekyll-theme-minimal
markdown: kramdown
